/* Generated By:JJTree: Do not edit this line. ASTAssigneePrefix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTAssigneePrefix extends SimpleNode {
  public ASTAssigneePrefix(int id) {
    super(id);
  }

  public ASTAssigneePrefix(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1003bbf8be57018c6ef430c910577dfe (do not edit this line) */
