/* Generated By:JJTree: Do not edit this line. ASTArrayDimensions.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayDimensions extends SimpleNode {
  public ASTArrayDimensions(int id) {
    super(id);
  }

  public ASTArrayDimensions(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0bb59970214007ba5044d026dd8f372b (do not edit this line) */
