/* Generated By:JJTree: Do not edit this line. ASTArraySuffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTArraySuffix extends SimpleNode {
  public ASTArraySuffix(int id) {
    super(id);
  }

  public ASTArraySuffix(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a37b1b508e0fdf8ada75691a01668c9f (do not edit this line) */
