/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTBool extends SimpleNode {
  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=685c87aebdef0cbe77b38d6f8ec8a3f8 (do not edit this line) */
