/* Generated By:JJTree: Do not edit this line. ASTCharLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTCharLiteral extends SimpleNode {
  public ASTCharLiteral(int id) {
    super(id);
  }

  public ASTCharLiteral(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c09748ba3dc5f86effb7aaaca526a79 (do not edit this line) */
