/* Generated By:JJTree: Do not edit this line. ASTConditionalAndExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalAndExpression extends SimpleNode {
  public ASTConditionalAndExpression(int id) {
    super(id);
  }

  public ASTConditionalAndExpression(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e669959975ecbf424081ecb8395afb14 (do not edit this line) */
