/* Generated By:JJTree: Do not edit this line. ASTDivideOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTDivideOperator extends SimpleNode {
  public ASTDivideOperator(int id) {
    super(id);
  }

  public ASTDivideOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a8711fa3dd3f1b61930a73e048af5f4 (do not edit this line) */
