/* Generated By:JJTree: Do not edit this line. ASTGreaterThanOrEqualOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTGreaterThanOrEqualOperator extends SimpleNode {
  public ASTGreaterThanOrEqualOperator(int id) {
    super(id);
  }

  public ASTGreaterThanOrEqualOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc449b0c7d98ef2a94d2921f2a602522 (do not edit this line) */
