/* Generated By:JJTree: Do not edit this line. ASTLessThanOrEqualOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTLessThanOrEqualOperator extends SimpleNode {
  public ASTLessThanOrEqualOperator(int id) {
    super(id);
  }

  public ASTLessThanOrEqualOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=69d68f67d99da8b8fac3d346abeabd11 (do not edit this line) */
