/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationLookahead.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTMethodDeclarationLookahead extends SimpleNode {
  public ASTMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTMethodDeclarationLookahead(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e5d38d96ed580b00a4291fcfdd40a82 (do not edit this line) */
