/* Generated By:JJTree: Do not edit this line. ASTModuloOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTModuloOperator extends SimpleNode {
  public ASTModuloOperator(int id) {
    super(id);
  }

  public ASTModuloOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea740f86348af8f94e976ff3c5ab5525 (do not edit this line) */
