/* Generated By:JJTree: Do not edit this line. ASTMultiplyOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTMultiplyOperator extends SimpleNode {
  public ASTMultiplyOperator(int id) {
    super(id);
  }

  public ASTMultiplyOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a505fa168449b320e62a9dc04f97f92c (do not edit this line) */
