/* Generated By:JJTree: Do not edit this line. ASTMinusOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTMinusOperator extends SimpleNode {
  public ASTMinusOperator(int id) {
    super(id);
  }

  public ASTMinusOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=65779e45296d3f480592a8511a4e368f (do not edit this line) */
