/* Generated By:JJTree: Do not edit this line. ASTName.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96ae1cf965e3ab70e0b47a68113ccc84 (do not edit this line) */
