/* Generated By:JJTree: Do not edit this line. ASTOrOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTOrOperator extends SimpleNode {
  public ASTOrOperator(int id) {
    super(id);
  }

  public ASTOrOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=804680f60d4c5b7896d335ea4130e507 (do not edit this line) */
