/* Generated By:JJTree: Do not edit this line. ASTPrimitive.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimitive extends SimpleNode {
  public ASTPrimitive(int id) {
    super(id);
  }

  public ASTPrimitive(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6036da737cad39baa841d34e1749c554 (do not edit this line) */
