/* Generated By:JJTree: Do not edit this line. ASTPlusOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTPlusOperator extends SimpleNode {
  public ASTPlusOperator(int id) {
    super(id);
  }

  public ASTPlusOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37209f07c7a223136b40b7c99ad25fd8 (do not edit this line) */
