/* Generated By:JJTree: Do not edit this line. ASTStatic.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTStatic extends SimpleNode {
  public ASTStatic(int id) {
    super(id);
  }

  public ASTStatic(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ca814f22e51b898657840ac48b8295d (do not edit this line) */
