/* Generated By:JJTree: Do not edit this line. ASTSuper.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTSuper extends SimpleNode {
  public ASTSuper(int id) {
    super(id);
  }

  public ASTSuper(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73287d63052d4f2bbea6d4a16aa650ed (do not edit this line) */
