/* Generated By:JJTree: Do not edit this line. ASTThis.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTThis extends SimpleNode {
  public ASTThis(int id) {
    super(id);
  }

  public ASTThis(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dea2afebd254f7a1b0628061bf516aa5 (do not edit this line) */
