/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26e49bb06fb877c8ef0992595ae622fa (do not edit this line) */
