/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariable extends SimpleNode {
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(OSTRAJavaParser p, int id) {
    super(p, id);
  }

  public String toString() {
    return super.toString() + "[" + value + "]";
  }
}
/* JavaCC - OriginalChecksum=f74c13f48b59dea18f42624b543f4001 (do not edit this line) */
