/* Generated By:JavaCC: Do not edit this line. OSTRAJavaParserTreeConstants.java Version 6.0_1 */
package cz.cvut.fit.ostrajava.Parser;

public interface OSTRAJavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTCLASS = 2;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 3;
  public int JJTFIELDDECLARATION = 4;
  public int JJTVARIABLEDECLARATOR = 5;
  public int JJTVARIABLE = 6;
  public int JJTVARIABLEINITIALIZER = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTMETHOD = 9;
  public int JJTFORMALPARAMETERS = 10;
  public int JJTFORMALPARAMETER = 11;
  public int JJTCONSTRUCTORDECLARATION = 12;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 13;
  public int JJTTYPE = 14;
  public int JJTBOOL = 15;
  public int JJTSTRING = 16;
  public int JJTNUMBER = 17;
  public int JJTFLOAT = 18;
  public int JJTRESULTTYPE = 19;
  public int JJTNAME = 20;
  public int JJTNAMELIST = 21;
  public int JJTEXPRESSION = 22;
  public int JJTASSIGNMENT = 23;
  public int JJTASSIGNEE = 24;
  public int JJTASSIGNEEPREFIX = 25;
  public int JJTASSIGNEESUFFIX = 26;
  public int JJTCONDITIONALEXPRESSION = 27;
  public int JJTCONDITIONALOREXPRESSION = 28;
  public int JJTOROPERATOR = 29;
  public int JJTCONDITIONALANDEXPRESSION = 30;
  public int JJTANDOPERATOR = 31;
  public int JJTEQUALITYEXPRESSION = 32;
  public int JJTEQUALOPERATOR = 33;
  public int JJTNOTEQUALOPERATOR = 34;
  public int JJTRELATIONALEXPRESSION = 35;
  public int JJTLESSTHANOPERATOR = 36;
  public int JJTGREATERTHANOPERATOR = 37;
  public int JJTLESSTHANOREQUALOPERATOR = 38;
  public int JJTGREATERTHANOREQUALOPERATOR = 39;
  public int JJTADDITIVEEXPRESSION = 40;
  public int JJTPLUSOPERATOR = 41;
  public int JJTMINUSOPERATOR = 42;
  public int JJTMULTIPLICATIVEEXPRESSION = 43;
  public int JJTMULTIPLYOPERATOR = 44;
  public int JJTDIVIDEOPERATOR = 45;
  public int JJTMODULOOPERATOR = 46;
  public int JJTUNARYEXPRESSION = 47;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 48;
  public int JJTPRIMARYEXPRESSION = 49;
  public int JJTPRIMARYPREFIX = 50;
  public int JJTTHIS = 51;
  public int JJTSUPER = 52;
  public int JJTPRIMARYSUFFIX = 53;
  public int JJTNUMBERLITERAL = 54;
  public int JJTFLOATLITERAL = 55;
  public int JJTSTRINGLITERAL = 56;
  public int JJTBOOLEANLITERAL = 57;
  public int JJTNULLLITERAL = 58;
  public int JJTARGUMENTS = 59;
  public int JJTALLOCATIONEXPRESSION = 60;
  public int JJTARRAYDIMENSIONS = 61;
  public int JJTSTATEMENT = 62;
  public int JJTBLOCK = 63;
  public int JJTLOCALVARIABLEDECLARATION = 64;
  public int JJTEMPTYSTATEMENT = 65;
  public int JJTSTATEMENTEXPRESSION = 66;
  public int JJTSWITCHSTATEMENT = 67;
  public int JJTSWITCHLABEL = 68;
  public int JJTIFSTATEMENT = 69;
  public int JJTWHILESTATEMENT = 70;
  public int JJTDOSTATEMENT = 71;
  public int JJTFORSTATEMENT = 72;
  public int JJTFORINIT = 73;
  public int JJTSTATEMENTEXPRESSIONLIST = 74;
  public int JJTFORUPDATE = 75;
  public int JJTBREAKSTATEMENT = 76;
  public int JJTCONTINUESTATEMENT = 77;
  public int JJTRETURNSTATEMENT = 78;
  public int JJTTHROWSTATEMENT = 79;
  public int JJTTRYSTATEMENT = 80;
  public int JJTPRINTSTATEMENT = 81;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Class",
    "MethodDeclarationLookahead",
    "FieldDeclaration",
    "VariableDeclarator",
    "Variable",
    "VariableInitializer",
    "MethodDeclaration",
    "Method",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Type",
    "Bool",
    "String",
    "Number",
    "Float",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "Assignment",
    "Assignee",
    "AssigneePrefix",
    "AssigneeSuffix",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "OrOperator",
    "ConditionalAndExpression",
    "AndOperator",
    "EqualityExpression",
    "EqualOperator",
    "NotEqualOperator",
    "RelationalExpression",
    "LessThanOperator",
    "GreaterThanOperator",
    "LessThanOrEqualOperator",
    "GreaterThanOrEqualOperator",
    "AdditiveExpression",
    "PlusOperator",
    "MinusOperator",
    "MultiplicativeExpression",
    "MultiplyOperator",
    "DivideOperator",
    "ModuloOperator",
    "UnaryExpression",
    "UnaryExpressionNotPlusMinus",
    "PrimaryExpression",
    "PrimaryPrefix",
    "This",
    "Super",
    "PrimarySuffix",
    "NumberLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "AllocationExpression",
    "ArrayDimensions",
    "Statement",
    "Block",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "TryStatement",
    "PrintStatement",
  };
}
/* JavaCC - OriginalChecksum=be24aad0ad249b0d1445f5322512819a (do not edit this line) */
