/* Generated By:JavaCC: Do not edit this line. OSTRAJavaParserTreeConstants.java Version 6.0_1 */
package cz.cvut.fit.ostrajava.Parser;

public interface OSTRAJavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTCLASS = 2;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 3;
  public int JJTFIELDDECLARATION = 4;
  public int JJTVARIABLEDECLARATOR = 5;
  public int JJTVARIABLE = 6;
  public int JJTVARIABLEINITIALIZER = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTSTATIC = 9;
  public int JJTMETHOD = 10;
  public int JJTFORMALPARAMETERS = 11;
  public int JJTFORMALPARAMETER = 12;
  public int JJTCONSTRUCTORDECLARATION = 13;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 14;
  public int JJTTYPE = 15;
  public int JJTARRAYTYPE = 16;
  public int JJTBOOL = 17;
  public int JJTCHAR = 18;
  public int JJTNUMBER = 19;
  public int JJTFLOAT = 20;
  public int JJTRESULTTYPE = 21;
  public int JJTNAME = 22;
  public int JJTNAMELIST = 23;
  public int JJTEXPRESSION = 24;
  public int JJTASSIGNMENT = 25;
  public int JJTASSIGNEE = 26;
  public int JJTTHIS = 27;
  public int JJTSUPER = 28;
  public int JJTCONDITIONALEXPRESSION = 29;
  public int JJTCONDITIONALOREXPRESSION = 30;
  public int JJTOROPERATOR = 31;
  public int JJTCONDITIONALANDEXPRESSION = 32;
  public int JJTANDOPERATOR = 33;
  public int JJTEQUALITYEXPRESSION = 34;
  public int JJTEQUALOPERATOR = 35;
  public int JJTNOTEQUALOPERATOR = 36;
  public int JJTRELATIONALEXPRESSION = 37;
  public int JJTLESSTHANOPERATOR = 38;
  public int JJTGREATERTHANOPERATOR = 39;
  public int JJTLESSTHANOREQUALOPERATOR = 40;
  public int JJTGREATERTHANOREQUALOPERATOR = 41;
  public int JJTADDITIVEEXPRESSION = 42;
  public int JJTPLUSOPERATOR = 43;
  public int JJTMINUSOPERATOR = 44;
  public int JJTMULTIPLICATIVEEXPRESSION = 45;
  public int JJTMULTIPLYOPERATOR = 46;
  public int JJTDIVIDEOPERATOR = 47;
  public int JJTMODULOOPERATOR = 48;
  public int JJTUNARYEXPRESSION = 49;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 50;
  public int JJTPRIMARYEXPRESSION = 51;
  public int JJTPRIMARYPREFIX = 52;
  public int JJTPRIMARYSUFFIX = 53;
  public int JJTNUMBERLITERAL = 54;
  public int JJTFLOATLITERAL = 55;
  public int JJTCHARLITERAL = 56;
  public int JJTSTRINGLITERAL = 57;
  public int JJTTRUE = 58;
  public int JJTFALSE = 59;
  public int JJTNULLLITERAL = 60;
  public int JJTARGUMENTS = 61;
  public int JJTALLOCATIONEXPRESSION = 62;
  public int JJTARRAYSUFFIX = 63;
  public int JJTSTATEMENT = 64;
  public int JJTBLOCK = 65;
  public int JJTLOCALVARIABLEDECLARATION = 66;
  public int JJTDEBUGSTATEMENT = 67;
  public int JJTEMPTYSTATEMENT = 68;
  public int JJTSTATEMENTEXPRESSION = 69;
  public int JJTSWITCHSTATEMENT = 70;
  public int JJTSWITCHLABEL = 71;
  public int JJTIFSTATEMENT = 72;
  public int JJTWHILESTATEMENT = 73;
  public int JJTSTATEMENTEXPRESSIONLIST = 74;
  public int JJTFORUPDATE = 75;
  public int JJTBREAKSTATEMENT = 76;
  public int JJTCONTINUESTATEMENT = 77;
  public int JJTRETURNSTATEMENT = 78;
  public int JJTTHROWSTATEMENT = 79;
  public int JJTTRYSTATEMENT = 80;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Class",
    "MethodDeclarationLookahead",
    "FieldDeclaration",
    "VariableDeclarator",
    "Variable",
    "VariableInitializer",
    "MethodDeclaration",
    "Static",
    "Method",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Type",
    "ArrayType",
    "Bool",
    "Char",
    "Number",
    "Float",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "Assignment",
    "Assignee",
    "This",
    "Super",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "OrOperator",
    "ConditionalAndExpression",
    "AndOperator",
    "EqualityExpression",
    "EqualOperator",
    "NotEqualOperator",
    "RelationalExpression",
    "LessThanOperator",
    "GreaterThanOperator",
    "LessThanOrEqualOperator",
    "GreaterThanOrEqualOperator",
    "AdditiveExpression",
    "PlusOperator",
    "MinusOperator",
    "MultiplicativeExpression",
    "MultiplyOperator",
    "DivideOperator",
    "ModuloOperator",
    "UnaryExpression",
    "UnaryExpressionNotPlusMinus",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "NumberLiteral",
    "FloatLiteral",
    "CharLiteral",
    "StringLiteral",
    "True",
    "False",
    "NullLiteral",
    "Arguments",
    "AllocationExpression",
    "ArraySuffix",
    "Statement",
    "Block",
    "LocalVariableDeclaration",
    "DebugStatement",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "TryStatement",
  };
}
/* JavaCC - OriginalChecksum=a71fc68703f37fc825701df34728239d (do not edit this line) */
