/* Generated By:JavaCC: Do not edit this line. OSTRAJavaParserTreeConstants.java Version 6.0_1 */
package cz.cvut.fit.ostrajava.Parser;

public interface OSTRAJavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTCLASS = 2;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 3;
  public int JJTFIELDDECLARATION = 4;
  public int JJTVARIABLEDECLARATOR = 5;
  public int JJTVARIABLE = 6;
  public int JJTVARIABLEINITIALIZER = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTMETHOD = 9;
  public int JJTFORMALPARAMETERS = 10;
  public int JJTFORMALPARAMETER = 11;
  public int JJTCONSTRUCTORDECLARATION = 12;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 13;
  public int JJTTYPE = 14;
  public int JJTBOOL = 15;
  public int JJTSTRING = 16;
  public int JJTNUMBER = 17;
  public int JJTFLOAT = 18;
  public int JJTRESULTTYPE = 19;
  public int JJTNAME = 20;
  public int JJTNAMELIST = 21;
  public int JJTEXPRESSION = 22;
  public int JJTASSIGNMENT = 23;
  public int JJTASSIGNMENTOPERATOR = 24;
  public int JJTCONDITIONALEXPRESSION = 25;
  public int JJTCONDITIONALOREXPRESSION = 26;
  public int JJTCONDITIONALANDEXPRESSION = 27;
  public int JJTEQUALITYEXPRESSION = 28;
  public int JJTINSTANCEOFEXPRESSION = 29;
  public int JJTRELATIONALEXPRESSION = 30;
  public int JJTADDITIVEEXPRESSION = 31;
  public int JJTMULTIPLICATIVEEXPRESSION = 32;
  public int JJTUNARYEXPRESSION = 33;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 34;
  public int JJTPRIMARYEXPRESSION = 35;
  public int JJTPRIMARYPREFIX = 36;
  public int JJTPRIMARYSUFFIX = 37;
  public int JJTNUMBERLITERAL = 38;
  public int JJTFLOATLITERAL = 39;
  public int JJTSTRINGLITERAL = 40;
  public int JJTBOOLEANLITERAL = 41;
  public int JJTNULLLITERAL = 42;
  public int JJTARGUMENTS = 43;
  public int JJTARGUMENTLIST = 44;
  public int JJTALLOCATIONEXPRESSION = 45;
  public int JJTARRAYDIMENSIONS = 46;
  public int JJTSTATEMENT = 47;
  public int JJTBLOCK = 48;
  public int JJTLOCALVARIABLEDECLARATION = 49;
  public int JJTEMPTYSTATEMENT = 50;
  public int JJTSTATEMENTEXPRESSION = 51;
  public int JJTSWITCHSTATEMENT = 52;
  public int JJTSWITCHLABEL = 53;
  public int JJTIFSTATEMENT = 54;
  public int JJTWHILESTATEMENT = 55;
  public int JJTDOSTATEMENT = 56;
  public int JJTFORSTATEMENT = 57;
  public int JJTFORINIT = 58;
  public int JJTSTATEMENTEXPRESSIONLIST = 59;
  public int JJTFORUPDATE = 60;
  public int JJTBREAKSTATEMENT = 61;
  public int JJTCONTINUESTATEMENT = 62;
  public int JJTRETURNSTATEMENT = 63;
  public int JJTTHROWSTATEMENT = 64;
  public int JJTTRYSTATEMENT = 65;
  public int JJTPRINTSTATEMENT = 66;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Class",
    "MethodDeclarationLookahead",
    "FieldDeclaration",
    "VariableDeclarator",
    "Variable",
    "VariableInitializer",
    "MethodDeclaration",
    "Method",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Type",
    "Bool",
    "String",
    "Number",
    "Float",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "Assignment",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "UnaryExpressionNotPlusMinus",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "NumberLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimensions",
    "Statement",
    "Block",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "TryStatement",
    "PrintStatement",
  };
}
/* JavaCC - OriginalChecksum=368b37c0218a3a7eb87f84d017b0a6b9 (do not edit this line) */
