/* Generated By:JJTree: Do not edit this line. ASTAssignee.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTAssignee extends SimpleNode {
  public ASTAssignee(int id) {
    super(id);
  }

  public ASTAssignee(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f299cefb3472ef697b2c8f479d7f89f4 (do not edit this line) */
