/* Generated By:JJTree: Do not edit this line. ASTAssigneeSuffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTAssigneeSuffix extends SimpleNode {
  public ASTAssigneeSuffix(int id) {
    super(id);
  }

  public ASTAssigneeSuffix(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e057f50e063b1b52223308fa8c29145 (do not edit this line) */
