/* Generated By:JJTree: Do not edit this line. ASTAndOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTAndOperator extends SimpleNode {
  public ASTAndOperator(int id) {
    super(id);
  }

  public ASTAndOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2789a6b702e31ff310abbe2a5ef5470a (do not edit this line) */
