/* Generated By:JJTree: Do not edit this line. ASTDebugStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTDebugStatement extends SimpleNode {
  public ASTDebugStatement(int id) {
    super(id);
  }

  public ASTDebugStatement(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f34dc30d3d7a436514c1e2c6e7a9673 (do not edit this line) */
