/* Generated By:JJTree: Do not edit this line. ASTEqualOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTEqualOperator extends SimpleNode {
  public ASTEqualOperator(int id) {
    super(id);
  }

  public ASTEqualOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5d72c370f499a024f089787e951805a (do not edit this line) */
