/* Generated By:JJTree: Do not edit this line. ASTFloat.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTFloat extends SimpleNode {
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79f7333b6ab45ab408cd6392c099a6b0 (do not edit this line) */
