/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTFloatLiteral extends SimpleNode {
  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90d1eb4bc791ea545914c22d2ad02d94 (do not edit this line) */
