/* Generated By:JJTree: Do not edit this line. ASTGreaterThanOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTGreaterThanOperator extends SimpleNode {
  public ASTGreaterThanOperator(int id) {
    super(id);
  }

  public ASTGreaterThanOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f29e549a71062cfaf4d80c2da0acad91 (do not edit this line) */
