/* Generated By:JJTree: Do not edit this line. ASTLessThanOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTLessThanOperator extends SimpleNode {
  public ASTLessThanOperator(int id) {
    super(id);
  }

  public ASTLessThanOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0b0d4a6245a7db91c3dc5e330e1064c (do not edit this line) */
