/* Generated By:JJTree: Do not edit this line. ASTNative.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTNative extends SimpleNode {
  public ASTNative(int id) {
    super(id);
  }

  public ASTNative(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf7863f1ea377e1e3a48e592b028e8b3 (do not edit this line) */
