/* Generated By:JJTree: Do not edit this line. ASTNumberValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTNumberValue extends SimpleNode {
  public ASTNumberValue(int id) {
    super(id);
  }

  public ASTNumberValue(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=581e24b915f09cc9b446886bc6b98c41 (do not edit this line) */
