/* Generated By:JJTree: Do not edit this line. ASTNegationOperator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTNegationOperator extends SimpleNode {
  public ASTNegationOperator(int id) {
    super(id);
  }

  public ASTNegationOperator(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbb00313d178653abdc5751695d213b7 (do not edit this line) */
