/* Generated By:JJTree: Do not edit this line. ASTPrintStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTPrintStatement extends SimpleNode {
  public ASTPrintStatement(int id) {
    super(id);
  }

  public ASTPrintStatement(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67fafc12e865cdba31dfd9910012a82e (do not edit this line) */
