/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cz.cvut.fit.ostrajava.Parser;

public
class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(OSTRAJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb2d4be7f808c1f0177c0c0589bf3cf5 (do not edit this line) */
